import { Link } from '@tanstack/react-router';
import { useEffect, useState, type ReactNode } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, Bell, Box, ChartNoAxesCombined, ChevronRight, CircleHelp, Cog, Factory, Flame, FlaskConical, Fullscreen, Gauge, Layers3, Leaf, Radio, RefreshCw, Settings2, ShieldCheck, SlidersHorizontal, TriangleAlert, TrendingUp, UserRound, Waves, Wrench, X, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import plant from '@/assets/coal-plant.jpg';
import { Chart, type ChartKind } from './chart';
export type PageId='overview'|'production'|'sorting'|'equipment'|'quality'|'energy'|'safety';
const menus=[{id:'overview',name:'综合总览',path:'/',icon:ChartNoAxesCombined},{id:'production',name:'生产监控',path:'/production',icon:Factory},{id:'sorting',name:'智能分选',path:'/sorting',icon:Layers3},{id:'equipment',name:'设备运维',path:'/equipment',icon:Wrench},{id:'quality',name:'煤质管理',path:'/quality',icon:FlaskConical},{id:'energy',name:'能源管理',path:'/energy',icon:Zap},{id:'safety',name:'安全环保',path:'/safety',icon:ShieldCheck}] as const;
const descriptions:Record<PageId,string>={overview:'全域感知 · 数据融合 · 智慧决策',production:'生产全流程监控 · 工艺协同 · 高效运行',sorting:'智能识别 · 精准分选 · 自适应优化',equipment:'设备全生命周期管理 · 预测性维护',quality:'全流程煤质检测 · 品质追溯 · 指标分析',energy:'能源精细化管控 · 降本增效 · 绿色生产',safety:'安全风险管控 · 环境实时监测 · 绿色发展'};
export function pageHead(id:PageId) { const name=menus.find(m=>m.id===id)?.name??'综合总览'; const title=`${name} · 智慧选煤厂`; return {meta:[{title},{name:'description',content:`智慧选煤厂${name}，${descriptions[id]}。`},{property:'og:title',content:title},{property:'og:description',content:`智慧选煤厂${name}数据与运行状态。`},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}; }
function Panel({title,children,note,icon:Icon=Activity,className=''}:{title:string;children:ReactNode;note?:ReactNode;icon?:typeof Activity;className?:string}) { return <section className={`glass panel ${className}`}><div className="panel-head"><h3 className="panel-title"><Icon/>{title}</h3><div className="panel-note">{note}</div></div>{children}</section>; }
function ChartPanel({title,kind='line',variant=0,tall=false,note='今日',className=''}:{title:string;kind?:ChartKind;variant?:number;tall?:boolean;note?:string;className?:string}) {return <Panel title={title} note={note} className={className}><Chart kind={kind} variant={variant} tall={tall} subject={title}/></Panel>;}
function Badge({children,type='success'}:{children:ReactNode;type?:'success'|'warning'|'danger'}) {return <span className={`badge ${type}`}>{children}</span>;}
const statSets:Record<PageId,{label:string;value:string;unit:string;change:string;icon:typeof Factory}[]>={
 overview:[{label:'今日原煤入洗量',value:'12,856',unit:'t',change:'12.8%',icon:Factory},{label:'今日精煤产量',value:'8,806',unit:'t',change:'8.6%',icon:Layers3},{label:'精煤回收率',value:'68.50',unit:'%',change:'2.3%',icon:RefreshCw},{label:'设备运行率',value:'98.60',unit:'%',change:'1.2%',icon:Cog},{label:'吨煤综合能耗',value:'4.28',unit:'kWh/t',change:'5.7%',icon:Zap}],
 production:[{label:'实时入洗量',value:'856',unit:'t/h',change:'6.2%',icon:Factory},{label:'累计精煤产量',value:'8,806',unit:'t',change:'8.6%',icon:Layers3},{label:'生产计划完成',value:'92.80',unit:'%',change:'3.1%',icon:Gauge},{label:'在线生产线',value:'4 / 4',unit:'条',change:'0.0%',icon:Activity},{label:'连续运行时间',value:'128',unit:'h',change:'12.5%',icon:Cog}],
 sorting:[{label:'今日分选量',value:'9,652',unit:'t',change:'9.2%',icon:Layers3},{label:'分选准确率',value:'96.80',unit:'%',change:'1.8%',icon:Gauge},{label:'矸石排出率',value:'99.20',unit:'%',change:'0.6%',icon:RefreshCw},{label:'智能识别次数',value:'128.6',unit:'万次',change:'12.1%',icon:Radio},{label:'算法响应时间',value:'12',unit:'ms',change:'8.5%',icon:Zap}],
 equipment:[{label:'设备总数',value:'186',unit:'台',change:'2.2%',icon:Cog},{label:'在线设备',value:'182',unit:'台',change:'1.1%',icon:Activity},{label:'设备完好率',value:'98.60',unit:'%',change:'1.2%',icon:ShieldCheck},{label:'待处理工单',value:'04',unit:'项',change:'20.0%',icon:Wrench},{label:'平均故障间隔',value:'2,680',unit:'h',change:'16.2%',icon:Gauge}],
 quality:[{label:'今日检测批次',value:'128',unit:'批',change:'8.5%',icon:FlaskConical},{label:'精煤灰分',value:'9.82',unit:'%',change:'1.6%',icon:Layers3},{label:'精煤水分',value:'8.45',unit:'%',change:'0.8%',icon:Waves},{label:'精煤热值',value:'6,850',unit:'kcal/kg',change:'2.6%',icon:Flame},{label:'煤质合格率',value:'99.20',unit:'%',change:'0.6%',icon:ShieldCheck}],
 energy:[{label:'今日用电量',value:'55,021',unit:'kWh',change:'5.7%',icon:Zap},{label:'吨煤电耗',value:'4.28',unit:'kWh/t',change:'5.7%',icon:Activity},{label:'循环水回用率',value:'96.80',unit:'%',change:'2.6%',icon:Waves},{label:'今日节约成本',value:'8,652',unit:'元',change:'15.2%',icon:TrendingUp},{label:'碳排放强度',value:'2.45',unit:'kg/t',change:'6.8%',icon:Leaf}],
 safety:[{label:'安全生产天数',value:'1,286',unit:'天',change:'持续安全',icon:ShieldCheck},{label:'在线监测点',value:'64',unit:'个',change:'100%',icon:Radio},{label:'隐患整改率',value:'100',unit:'%',change:'全部闭环',icon:Wrench},{label:'环保达标率',value:'99.80',unit:'%',change:'0.3%',icon:Leaf},{label:'实时粉尘浓度',value:'0.82',unit:'mg/m³',change:'12.5%',icon:Waves}]
};
const alerts=[{title:'301#皮带机轴承温度偏高',detail:'设备预警 · 当前温度 72.6°C',time:'14:28:36',level:'warning'},{title:'2#重介旋流器压力波动',detail:'工艺提示 · 压力偏差 +0.02 MPa',time:'14:15:08',level:'warning'},{title:'煤质在线检测已完成',detail:'系统消息 · 第128批次检测合格',time:'14:08:52',level:'success'}];
function AlertList({onOpen}:{onOpen:()=>void}) { return <Panel title="实时预警动态" icon={Bell} note={<Button variant="ghost" size="sm" onClick={onOpen}>查看全部<ChevronRight/></Button>}>{alerts.map(a=><div className="alert-row" key={a.title}><TriangleAlert/><div><strong>{a.title}</strong><p>{a.detail}</p></div><span className="alert-time">{a.time.slice(0,5)}</span></div>)}</Panel>; }
function PlantView({title='厂区数字全景',large=false}:{title?:string;large?:boolean}) {return <section className={`glass plant-view ${large?'wide-panel':''}`}><img className="plant-image" src={plant} alt="现代化选煤厂实景" width={1920} height={1024}/><div className="plant-shade"/><div className="panel-head"><span className="panel-title"><Factory/>{title}</span><span className="plant-top-label">DIGITAL PLANT</span></div><div className="plant-tags"><span className="plant-tag">原煤仓 · 在线</span><span className="plant-tag">主洗车间 · 运行中</span><span className="plant-tag">精煤仓 · 在线</span></div><div className="plant-bottom"><div><h3>智能选煤 · 全域协同</h3><p>4条生产线 / 186台设备 / 64个监测点</p></div><span className="live-dot">系统运行正常</span></div></section>;}
const batches=[['QC-20261008-128','精煤','9.82','8.45','6,850','合格'],['QC-20261008-127','精煤','9.76','8.32','6,920','合格'],['QC-20261008-126','中煤','24.65','10.21','4,560','合格'],['QC-20261008-125','精煤','10.12','8.56','6,780','合格'],['QC-20261008-124','原煤','28.42','9.12','4,250','待复检']];
function DataTable({mode='production',filter='全部'}:{mode?:'production'|'quality'|'equipment'|'safety';filter?:string}) {
 const headers=mode==='quality'?['检测批次','产品类型','灰分 %','水分 %','热值 kcal/kg','结果']:mode==='equipment'?['设备编号','设备名称','运行温度','振动 mm/s','健康评分','状态']:mode==='safety'?['监测点位','监测类型','实时数值','预警阈值','更新时间','状态']:['生产线','入洗量 t/h','精煤量 t/h','回收率','状态'];
 const rows=mode==='quality'?batches:mode==='equipment'?[['EQ-301','301#皮带机','72.6°C','2.8','82','预警'],['EQ-205','2#重介旋流器','46.2°C','1.2','96','运行中'],['EQ-108','1#振动筛','38.5°C','1.8','94','运行中'],['EQ-402','4#离心机','52.1°C','1.5','98','运行中'],['EQ-501','循环水泵','41.2°C','1.1','97','运行中']]:mode==='safety'?[['主洗车间','粉尘浓度','0.82 mg/m³','4.00 mg/m³','14:33:05','正常'],['煤泥水处理','排水 pH','7.2','6.0 – 9.0','14:33:02','正常'],['原煤输送廊','噪声','62.5 dB','85.0 dB','14:33:05','正常'],['厂区东侧','PM2.5','28 μg/m³','75 μg/m³','14:33:01','正常']]:[['1#主洗生产线','286.5','196.3','68.52%','运行中'],['2#主洗生产线','278.2','190.6','68.51%','运行中'],['3#智能干选线','165.8','113.5','68.46%','运行中'],['4#煤泥回收线','125.5','85.6','68.21%','运行中']];
 const filtered=filter==='全部'?rows:rows.filter(r=>r.includes(filter));
 return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===r.length-1?<Badge type={['预警','待复检'].includes(c)?'warning':'success'}>{c}</Badge>:c}</td>)}</tr>)}</tbody></table>{filtered.length===0&&<div className="empty-note">暂无符合条件的记录</div>}</div>;
}
function Flow() {const nodes=[{name:'原煤入仓',value:'856 t/h',icon:Box},{name:'筛分破碎',value:'运行正常',icon:Cog},{name:'重介分选',value:'1.45 g/cm³',icon:Layers3},{name:'脱水回收',value:'96.8%',icon:Waves},{name:'精煤入仓',value:'586 t/h',icon:Factory}];return <div className="flow">{nodes.map((n,i)=><div className="contents" key={n.name}><div className="flow-node"><n.icon/><strong>{n.name}</strong><Badge>{n.value}</Badge></div>{i<4&&<ArrowRight className="flow-arrow" size={18}/>}</div>)}</div>;}
function Filter({value,onChange,options}:{value:string;onChange:(s:string)=>void;options:string[]}) {return <select aria-label="筛选数据" className="filter-select" value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select>;}
export function PlatformPage({page}:{page:PageId}) {
 const [period,setPeriod]=useState('今日'); const [filter,setFilter]=useState('全部'); const [modal,setModal]=useState<'alerts'|'settings'|'help'|'account'|'parameters'|null>(null); const [notice,setNotice]=useState(''); const [dateText,setDateText]=useState('2026-10-08 14:33:00'); const [acknowledged,setAcknowledged]=useState(false); const [density,setDensity]=useState('1.45'); const [auto,setAuto]=useState(true);
 useEffect(()=>{const tick=()=>setDateText(new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()));tick();const id=setInterval(tick,1000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(id);},[notice]);
 const variant=period==='今日'?0:period==='本周'?2:4;
 function exportData() {const rows=statSets[page];const csv='\ufeff指标,数值,单位,统计范围\n'+rows.map(s=>`${s.label},"${s.value}",${s.unit},${period}`).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`智慧选煤厂-${menus.find(m=>m.id===page)?.name}-${period}.csv`;a.click();URL.revokeObjectURL(url);setNotice('报表已导出（演示数据）');}
 async function fullScreen() {try {if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch {setNotice('当前浏览器不支持全屏显示');}}
 return <div className="platform"><img className="app-background" src={plant} alt="" width={1920} height={1024}/><header className="topbar"><div className="brand"><span className="brand-icon"><Factory size={27}/></span><div><h1>智慧选煤厂<span className="text-primary">平台</span></h1><p>SMART COAL PREPARATION PLATFORM</p></div></div><nav className="main-nav" aria-label="主导航">{menus.map(m=><Link key={m.id} to={m.path} className={`nav-item ${page===m.id?'active':''}`}><m.icon/><span>{m.name}</span></Link>)}</nav><div className="header-tools"><Button title="全屏显示" aria-label="全屏显示" variant="ghost" size="icon" onClick={fullScreen}><Fullscreen/></Button><Button title="消息中心" aria-label="消息中心" variant="ghost" size="icon" onClick={()=>setModal('alerts')}><Bell/></Button><span className="header-divider"/><Button title="账户信息" aria-label="账户信息" variant="ghost" size="icon" onClick={()=>setModal('account')}><span className="avatar"><UserRound size={17}/></span></Button></div></header>
 <main className="content"><div className="page-heading"><div><h2>{menus.find(m=>m.id===page)?.name}</h2><div className="page-subtitle">{descriptions[page]}<span className="mx-3">/</span><span>演示数据</span></div></div><div className="heading-actions"><span className="live-dot">数据更新正常</span><div className="segment">{['今日','本周','本月'].map(p=><Button variant="ghost" size="sm" key={p} className={period===p?'selected':''} onClick={()=>setPeriod(p)}>{p}</Button>)}</div><Button variant="outline" size="sm" onClick={exportData}><ArrowDownToLine/>导出报表</Button><Button variant="ghost" size="icon" title="显示设置" aria-label="显示设置" onClick={()=>setModal('settings')}><Settings2/></Button></div></div>
 <div className="stat-grid">{statSets[page].map((s,i)=><div className="glass stat" key={s.label}><div className="stat-label">{s.label.replace('今日',period)}<s.icon className="stat-icon"/></div><div className="stat-value">{variant&&i<2?(Number(s.value.replaceAll(',',''))*(variant===2?6.4:24.5)).toLocaleString('en-US',{maximumFractionDigits:0}):s.value}<small>{s.unit}</small></div><div className="stat-foot">较上一{period==='今日'?'日':period==='本周'?'周':'月'}<span>{s.change.includes('%')?`${page==='energy'||i===4?'↓':'↑'} ${s.change}`:s.change}</span></div></div>)}</div>
 {page==='overview'&&<><div className="overview-grid"><ChartPanel title="原煤入洗与精煤产量" variant={variant} note="单位：t/h"/><PlantView/><ChartPanel title="产品结构分析" kind="donut" note="产率占比"/></div><div className="overview-bottom"><Panel title="生产线实时运行" icon={Factory} note={<span className="live-dot">4条在线</span>}><DataTable/></Panel><ChartPanel title="煤质综合指标" kind="radar" note="实时 / 目标"/><AlertList onOpen={()=>setModal('alerts')}/></div><div className="three-grid mt-[18px]"><ChartPanel title="各班次生产对比" kind="bar" variant={variant} note="单位：t"/><ChartPanel title="设备运行健康度" kind="donut" variant={1} note="182 / 186 台在线"/><ChartPanel title="分系统能耗分析" kind="stack" variant={variant} note="单位：kWh"/></div></>}
 {page==='production'&&<div className="page-grid production-layout"><Panel title="选煤工艺全流程" className="wide-panel" icon={Factory} note={<span className="live-dot">自动控制 · 运行正常</span>}><Flow/></Panel><ChartPanel title="生产实时趋势" variant={variant} tall note="入洗量 / 精煤量 · t/h"/><Panel title="关键工艺参数" icon={SlidersHorizontal} note="实时采集"><div className="alert-row"><Activity/><div><strong>重介悬浮液密度</strong><p>目标范围 1.40–1.50 g/cm³</p></div><span className="stat-value text-primary">{density}</span></div><div className="alert-row"><Waves/><div><strong>旋流器入口压力</strong><p>控制范围 0.20–0.30 MPa</p></div><span className="stat-value">0.26</span></div><div className="alert-row"><Gauge/><div><strong>浮选药剂流量</strong><p>自动调节 · 稳定运行</p></div><span className="stat-value text-success">12.8</span></div><Button variant="outline" className="mt-5 w-full" onClick={()=>setModal('parameters')}><SlidersHorizontal/>查看工艺设置</Button></Panel><Panel title="生产班次记录" icon={Factory} note={<Filter value={filter} onChange={setFilter} options={['全部','运行中']}/>}><DataTable filter={filter}/></Panel><ChartPanel title="班次计划与实际产量" kind="bar" variant={variant}/></div>}
 {page==='sorting'&&<><div className="page-grid split-layout"><PlantView title="智能干选运行全景"/><div className="page-grid split-layout"><ChartPanel title="AI分选准确率" kind="gauge" note="模型 V3.2"/><ChartPanel title="原料成分识别" kind="donut" note="识别占比"/></div><Panel title="分选策略与模型状态" icon={Layers3} note={<Badge>模型在线</Badge>}><Flow/><div className="flex items-center justify-between border-t border-border py-4"><div><strong>自适应密度控制</strong><p className="text-muted-foreground mt-2 text-xs">当前设定密度 {density} g/cm³</p></div><Button variant={auto?'default':'outline'} size="sm" onClick={()=>{setAuto(!auto);setNotice(`演示控制已切换为${auto?'手动':'自动'}模式`);}}><RefreshCw/>{auto?'自动模式':'手动模式'}</Button></div></Panel><ChartPanel title="分选效果综合评估" kind="radar"/></div><div className="three-grid mt-[18px]"><ChartPanel title="分选产量趋势" variant={variant}/><ChartPanel title="分选设备产能对比" kind="bar" variant={variant}/><Panel title="分选检测批次" icon={FlaskConical}><DataTable mode="quality"/></Panel></div></>}
 {page==='equipment'&&<><div className="device-grid">{[{name:'301#皮带输送机',id:'EQ-301',temp:'72.6',score:'82',warn:true,icon:Cog},{name:'2#重介旋流器',id:'EQ-205',temp:'46.2',score:'96',warn:false,icon:Layers3},{name:'1#高频振动筛',id:'EQ-108',temp:'38.5',score:'94',warn:false,icon:Activity},{name:'4#精煤离心机',id:'EQ-402',temp:'52.1',score:'98',warn:false,icon:RefreshCw}].map(d=><section className="glass device" key={d.id}><div className="flex justify-between"><span className="panel-note">{d.id}</span><Badge type={d.warn?'warning':'success'}>{d.warn?'温度预警':'运行正常'}</Badge></div><d.icon className="device-icon" size={38}/><h3>{d.name}</h3><div className="device-metrics"><div>轴承温度<strong>{d.temp}<small className="text-xs"> °C</small></strong></div><div>健康评分<strong>{d.score}<small className="text-xs"> /100</small></strong></div></div><Button variant="ghost" size="sm" className="mt-4 w-full" onClick={()=>{setModal('alerts');}}>查看运行记录<ChevronRight/></Button></section>)}</div><div className="page-grid production-layout mt-[18px]"><Panel title="设备运行台账" icon={Wrench} note={<Filter value={filter} onChange={setFilter} options={['全部','运行中','预警']}/>}><DataTable mode="equipment" filter={filter}/></Panel><ChartPanel title="设备完好率" kind="donut" variant={1}/><ChartPanel title="设备负载趋势" variant={variant}/><AlertList onOpen={()=>setModal('alerts')}/></div></>}
 {page==='quality'&&<><div className="three-grid"><ChartPanel title="煤质指标雷达分析" kind="radar"/><ChartPanel title="煤质指标变化趋势" variant={variant} note="灰分 / 水分趋势"/><ChartPanel title="产品品质分布" kind="donut" note="产品类型占比"/></div><div className="page-grid production-layout mt-[18px]"><Panel title="煤质检测与追溯" icon={FlaskConical} note={<Filter value={filter} onChange={setFilter} options={['全部','精煤','中煤','原煤','待复检']}/>}><DataTable mode="quality" filter={filter}/></Panel><Panel title="质量控制目标" icon={ShieldCheck} note={<Badge>检测正常</Badge>}>{[{name:'精煤灰分',value:'9.82%',goal:'≤ 10.50%'},{name:'精煤全硫',value:'0.42%',goal:'≤ 0.60%'},{name:'精煤热值',value:'6,850 kcal/kg',goal:'≥ 6,500 kcal/kg'},{name:'在线检测频率',value:'每 5 分钟',goal:'128批次 / 今日'}].map(x=><div className="alert-row" key={x.name}><FlaskConical/><div><strong>{x.name}</strong><p>目标 {x.goal}</p></div><span className="ml-auto text-success">{x.value}</span></div>)}</Panel></div></>}
 {page==='energy'&&<><div className="energy-banner"><Leaf className="text-success" size={56}/><div><h3>绿色选煤 · 能效优化</h3><div className="big-number">18.6% <small className="text-muted-foreground text-sm">综合节能率</small></div></div><div className="energy-details"><div className="text-muted-foreground">累计减少碳排放<strong>286.5 <small className="text-xs">t CO₂</small></strong></div><div className="text-muted-foreground">累计节约能源成本<strong>128.6 <small className="text-xs">万元</small></strong></div></div></div><div className="page-grid production-layout"><ChartPanel title="分系统能耗趋势" kind="stack" variant={variant} tall note="单位：kWh"/><ChartPanel title="能源消耗结构" kind="donut"/><ChartPanel title="班次能效对比" kind="bar" variant={variant}/><Panel title="能源监测台账" icon={Zap}><div className="table-wrap"><table><thead><tr>{['系统','电耗 kWh','占比','状态'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{[['重介分选','24,209','44.0%'],['皮带输送','16,506','30.0%'],['煤泥回收','8,253','15.0%'],['辅助系统','6,053','11.0%']].map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}<td><Badge>正常</Badge></td></tr>)}</tbody></table></div></Panel></div></>}
 {page==='safety'&&<><div className="safety-layout"><Panel title="安全生产综合态势" icon={ShieldCheck} note={<Badge>安全运行</Badge>}><div className="safety-status"><ShieldCheck className="safety-shield"/><div><strong>1,286 <small className="text-base">天</small></strong><p className="text-muted-foreground mt-2">连续安全生产 · 零重大事故</p></div></div>{[{title:'风险点监控',detail:'32 / 32 个风险点全部受控'},{title:'安全巡检',detail:'今日 16 项巡检已完成'},{title:'隐患治理',detail:'本月 12 项隐患全部闭环'}].map(a=><div className="alert-row" key={a.title}><ShieldCheck/><div><strong>{a.title}</strong><p>{a.detail}</p></div><span className="live-dot ml-auto">正常</span></div>)}</Panel><PlantView title="厂区环境监测全景"/></div><div className="three-grid mt-[18px]"><ChartPanel title="环境监测变化趋势" variant={variant} note="粉尘 / 噪声"/><ChartPanel title="环保综合评价" kind="radar"/><ChartPanel title="环保设施运行占比" kind="donut"/></div><Panel title="环境在线监测记录" icon={Leaf} className="mt-[18px]" note={<span className="live-dot">64个监测点在线</span>}><DataTable mode="safety"/></Panel></>}
 <footer className="footer"><span className="flex items-center gap-2"><span className="live-dot">平台运行正常</span><span>数据采集延时 128ms</span><span className="hidden sm:inline">· 工业互联网数据中心</span></span><span className="font-mono">{dateText} CST <span className="mx-2">|</span> V 2.6.0</span></footer></main>
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section role="dialog" aria-modal="true" aria-label={modal==='alerts'?'消息中心':'平台设置'} className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h3>{modal==='alerts'?'消息与预警中心':modal==='settings'?'显示设置':modal==='account'?'账户信息':modal==='parameters'?'工艺参数设置':'平台信息'}</h3><Button variant="ghost" size="icon" aria-label="关闭窗口" onClick={()=>setModal(null)}><X/></Button></div>{modal==='alerts'?<>{alerts.map(a=><div className="alert-row" key={a.title}><TriangleAlert/><div><strong>{a.title}</strong><p>{a.detail}</p></div><span className="alert-time">{a.time}</span><Badge type={acknowledged?'success':'warning'}>{acknowledged?'已确认':'待确认'}</Badge></div>)}<Button className="mt-6" onClick={()=>{setAcknowledged(true);setNotice('全部演示消息已确认');}} disabled={acknowledged}><ShieldCheck/>{acknowledged?'全部已确认':'全部确认'}</Button></>:modal==='settings'?<><div className="flex justify-between items-center py-4"><span>统计范围</span><Filter value={period} onChange={setPeriod} options={['今日','本周','本月']}/></div><div className="flex justify-between items-center py-4"><span>全屏显示</span><Button variant="outline" onClick={fullScreen}><Fullscreen/>切换全屏</Button></div><div className="alert-row"><CircleHelp/><div><strong>智慧选煤厂 V2.6.0</strong><p>当前为演示环境，展示数据不代表真实生产情况。</p></div></div></>:modal==='account'?<div className="flex items-center gap-4 py-6"><span className="avatar"><UserRound/></span><div><strong>厂区管理员 · 演示账户</strong><p className="text-muted-foreground mt-2">当前权限：查看、筛选与导出演示数据</p></div></div>:modal==='parameters'?<><label className="flex items-center justify-between py-5">重介悬浮液密度 (g/cm³)<input aria-label="重介悬浮液密度" type="number" min="1.4" max="1.5" step="0.01" value={density} onChange={e=>setDensity(e.target.value)} className="filter-select w-28"/></label><p className="text-muted-foreground">允许范围：1.40–1.50，仅调整演示参数。</p><Button className="mt-6" onClick={()=>{if(Number(density)<1.4||Number(density)>1.5){setNotice('请输入1.40–1.50范围内的密度');return;}setModal(null);setNotice('演示工艺参数已更新');}}><SlidersHorizontal/>保存参数</Button></>:null}</section></div>}{notice&&<div role="status" className="notice">{notice}</div>}</div>;
}
